language: python
python:
- '3.6'
install: pip install django
script: true
deploy:
  provider: pypi
  user: serioeseGmbH
  on:
    branch: master
  password:
    secure: l5kgAarZwlstZKbKujVF1pUY6HpirOvTqjmg9v9mNSCQAjSgLM4zUpjpwIsiMQzWXPVBpS4UIVmXV5JUDyXpMb1zqmBHPBt7xmQNDlYi88VqzcpfxXEJl298w8IIS3Uc2t6nEYanUd29t1hIiE7YDNAu0oAXrGAvvhgB1J+zmcB2nqT8CQH99Fv5+2xbPytInoNB4MfRi9+s2cSlN5XwdMEe7quWHX4dcjP6FgSUGXhdImKdYz5Qq7c1HWBQJF6ifRZamokAmUX7sYtxJQGOMT7MgDL+FKfFtvXWGf8+zV8kNiDtPNAW5DJKisjklbbnDLYLBBThiY8Oz1BPkd3G4Lw4fSCDEa+jZORQDXkTwT3OOndwhfG4iIDigN/tF5qwa7Ocrb/EI+1dSekd1zQTyT1lKgAUJaYNnRa6nhxXYFBbX/RtHGpettCMxFwiPeVfgMFxde4XX+BqLFxq8xIwdG2g5/9UgQAYsvo44b4i5LH6uyge8JW58FCfHKdy2f894jBdAcfCA9LeZ+QM+VLTtQf044sGd8KXTPFL1l6FhzDHo8XVVTkg2pujDnlAI/0F7czZlD1UoYTVhTETEUfhY6Tm/NuhZAKyGdr3WGSacvFEcN1ank7l4w5Yoznx38TLyAghrTbeS7IMeF9O+AQ1plftPFmtn5Kv3tZQvHvp3uo=
